import React from 'react'

import Layout from '../../components/layout'
import ALink from '../../components/alink'

const ComicsPage = () => (
  <Layout title='What '>
    <div className='page_title'>An Examination of Comics</div>
    <div className='page_subtitle'>An Examination of Comics by Comparison to other Mediums</div>

    <div className='note'><p>This paper was written as coursework for CMS.400, Media Systems and Texts.<br/>November 2016</p></div>

    <div className='paragraph'><p>Comics are an interesting medium because of how they combine the more traditional, formal medium of literature with the more visual, traditionally artistic medium of images. This melding of mediums is interesting in how it provides comics with a diversity of range in conveying information and expressing complex ideas. Despite this great range, mainstream comics tend towards a focus on either fictional narratives or commentary, whether social or political, as seen with political cartoons. This tendency is not due to a limitation of comics as a medium, but to the advantages and disadvantages that comics have in comparison to other media forms. Comics are exceptional at delivering a focused meaning, blending information with commentary, and exaggerating the significant elements of a scene or story. This makes comics ideal for a narrative or argumentative focus, and is best understood through the comparison to other mediums.</p></div>
    <hr></hr>
    <div className='paragraph'><p>Starting with written works, literature has been a dominant form of storage media for many centuries. This dominance is due in large part to the applicability of the abstract ideas contained in written words. Words can be combined to describe any multitude of meanings; and these meanings can be furthered, enhanced, and made more complex by adding to the description. The abstract nature of the component words and the way they are brought together to transcribe complex thought is the primary benefit of this form. Points are explicitly; while there is room for interpretation in the ambiguous, statements made are consistent in their meaning.</p></div>
    <div className='paragraph'><p>Comics directly draw from literature in many ways. The most obvious is the written component, seen in how many comics use words to express speech, show sound, and bring context to a visual situation. The less obvious but more influential connection is the reliance on sequence. Literature generally has a very structured form with words, sentences, paragraphs, and chapters in a set sequence that must be followed for the proper conveyance of information. Similarly, comics rely on a sequence of images to properly convey a narrative or message. For this reason, comics are often considered “sequential art,” a term coined by comic artist Will Eisner and further explained by fellow comic artist Scott McCloud. For this reason, written word can be considered one half of the “melded” mediums that make up comics.</p></div>
    <div className='paragraph'><p>Comic’s use of words and sequence allows the literary components of comics to make use of all advantages held by traditional literature. Where this usage and these forms differ is the use of description and verbs. When actions take place, or a setting is introduced, a writer paints a picture of the visual elements that a reader must imagine for themselves. With comics, the images and similar visual elements take on this role. It is a more literal expression of the writing technique “Show, don’t tell.” A scene does need be told; as it is shown visually. This holds true for actions as well; as an action can be shown, instead of described with verbs and adverbs. This disparity is beneficial in many ways, but also acts as a double-edged sword for comics as a form. Having a visual setting represented by a visual image removes a layer of abstraction between the viewer and the creator's understanding of the scene. This gives the form more accessibility and ease of consumption. This difference is a disadvantage when a creator wants to express an abstract idea or setting, or simply wants to leave information up to the imagination of the reader.</p></div>
    <div className='paragraph'><p>This disadvantage can be seen in the many visual adaptations of works of Lovecraftian horror. Lovecraftian horror is a genre of horror that focuses on unknown and unknowable cosmic forces. To properly convey these abstract themes and entities, the works often make use of abstract description and unreliable narrators. This is what allows such horror authors to describe these metaphysical, multidimensional creatures. With visual adaptations, physical characteristics and senses of scale can be captured magnificently, however there is often a loss of the abstract elements of the source material. In cases such as these, expression of the creator's view becomes more difficult when also attempting to maintain the visual elements of the comic form.</p></div>
    <hr></hr>
    <div className='paragraph'><p>Looking at images, the other half of the “melded” medium of comics, images can be any medium ranging from paintings to pictographs. Images hold an advantage among media forms in how well they project information. Humans are adapted to pull abstract information from a visual environment. This information can be simple, such as an object’s position and orientation, or more complex, such as a character’s emotions of passion or dread. For this reason, images are a very information dense form. Where this differs from written work is that the information found in images is often implied; it is interpreted by the viewer, reflecting pieces of information that they already understand. This interpretation can be seen with simple information by examining optical illusions. These illusions are often designed to play with the shifting interpretation of the viewer. An example is the vase illusion, which displays either a vase in the center of the image or two symmetric faces on the outer edge. This interpretation can also be seen with more complex information. An example of this is the mixed perceptions of emotion in works of art, such as Leonardo Da Vinci’s Mona Lisa, and in photographs, such as Dorothea Lange’s Migrant Mother. This mixture of perception and room for interpretation contrasts written word, in that words are used as pieces of information with concrete, predefined meanings.</p></div>
    <div className='paragraph'><p>Comics gain many advantages through the incorporation of images and visual elements. There is the previously mentioned advantage of accessibility, provided by substituting literal elements with visual ones. There is also the advantage of incorporating pre-established styles and techniques, used in more traditional visual arts, to elicit effects similar to the connotations lost with words. The main difference between images and comics as a form is the loss of interpretation. With images, abstract information is harvested by the viewer from the work, but adding abstract information, via words, takes away some of the interpretation ability of the viewer. An example would be understanding the emotion of a visual character with a written explanation. If the viewer’s interpretation of the visuals matches the information provided in the written portion, the inclusion of written words may be affirmative or redundant. If the interpretations conflict, the written portion creates a dissonance in the work, taking away from the meaning of both parts. This loss of interpretation when adding words to visuals is similar to the loss of imagination when adding visuals to words. These two sets of contrasts show how comics are more effective at delivering a focused meaning, but less effect when creating an interpreted work.</p></div>
    <hr></hr>
    <div className='paragraph'><p>Comparing the comic as a medium to its two “source mediums” provides a useful context for understanding the abilities of comics, but does not contribute as much to understanding its purpose and use. For this understanding, other comparisons are more useful. An interesting, though seldom made, comparison is that of a comic to an academic data figure. It could be argued that a figure is a type of comic, as it has a visual element in its data display, as well as a literal element, in its caption and notation; however these forms are not equivalent for a number of reasons. The foremost is the separation of caption from figure. Though these two elements are paired in academic works, the caption and figure are kept distinctly apart. The nature of their codependence, or dependence on each other to deliver meaning, is what marks them as a singular medium. The separation of text and visual elements is a significant discrepancy from the melding of visual and literary elements that make up a standard comic. Similar discrepancies exist in the lack of panel based format and use of speech bubbles; however these are not strictly held attributes of comics, more so elements of style used for their convenience in printing and understanding speech. For these reasons, these two media forms can be considered distinct.</p></div>
    <div className='paragraph'><p>Looking at the purpose of academic figures, the most basic purpose of these figures is to convey data. Figures are used to convey this data in a more consumable form, and is preferred to the alternative methods of tables and walls of text. Figures also have the secondary benefits of allowing readers to draw more abstract conclusions about the data being displayed. If two groups of data points are significantly separated from each other, a viewer is able to easily understand the differences in magnitudes or intensities of the two groups. Similarly, if a writer decides to display data as a part of a line, rather than individual points, the writer is able to convey to the reader that there is a relation that extends between the points of data. Captions function with a similar purpose, as they are meant to guide the reader through the figure. They explain the context of the figure, highlight what is especially noteworthy, and convey the primary conclusion that can be drawn from the data. In this sense, the purpose of a data figure is to take data and display it in a manner that conveys the desired meaning.</p></div>
    <div className='paragraph'><p>Despite the similarities of form, this purpose contrasts the more general use of comics. Comics are able to portray a large range of information, from fictional narrative to political argument, but generally are not used in an academic context. Comics can portray data; but this is generally done in the context of an argument, with the use of high level data analysis, instead of the multilevel data analysis used in academics. This distinction is important, because it ties purpose to form. In academics, the figure is the data, while the caption is the words of the researcher. As data is interpreted through levels of analysis, it is more closely tied to the perspective and bias of the researcher. In an academic context, having levels of data ranging from raw data to high level analysis is important because it shows the path from data to conclusion, and allows for distinction between what is being studied and the conclusions of the researcher doing the studying. This is expressed, in form, by keeping the words of the researcher separate from the data of the figure. A more comic-like form would not be as acceptable for academic purpose, because of how it combines words and images as one message. In a way, this also explains the strength of comics when applied to political argument. A comic is able to tie a fact or quote, displayed as words or speech, to the creator’s interpretation and perspective, displayed as images, often in exaggeration.</p></div>
    <hr></hr>
    <div className='paragraph'><p>Another interesting comparison that is not often directly made is that of live action video to comics. This comparison may seem to jump a couple of mediums, but it seems especially relevant considering the upswing of comic to live action adaptations in recent years. Between these two mediums, there are two major differences that set them apart. The first is the live-action element of video that is not often present in comics. This element is removed via the abstraction visual information used in comics to create a cartoon style. Though a cartoon style is not mandatory for a work to be considered a comic, any drawn medium has some level of abstraction due to the lack of one to one representation of reality. This idea is explored in Scott McCloud’s Understanding Comics. McCloud goes further, and explains how much of comics exists on a spectrum between pure abstract word and pure visual “reality.” This idea extends to the use of abstract symbols as visual words or sounds, replacing the auditory elements of video.</p></div>
    <div className='paragraph'><p>The second major difference between the mediums is the video’s existence in time and dependence on time to portray its meaning. A video frozen in time is incomplete and only tells a fraction of the greater picture. This is not true for comics, and other static mediums, such as pictures or written works. A comic has only one state, and all of the information meant to be portrayed exists in this state. This difference is a disparity of dimension between the two mediums, and justly creates many advantages and disadvantages between the two forms.</p></div>
    <div className='paragraph'><p>In terms of what is gained when confining a medium to a singular state, a piece of media in a single state is more consumable. Seeing it at any point in time is equivalent to any other point and carries the full meaning. It does not have a minimum time requirement associated with its message, and a viewer can take as much time as desired viewing the media as a whole and drawing conclusions. In a similar way, the method of consumption is less restrictive. With video, the experience is designed around the premise that it will be consumed linearly, from start to finish over a set amount of time. Reversing the play direction or offsetting the start and finish times upsets the meaning of the media. With images and written works, the same expectation does not hold true. With an image, a creator may try to guide the viewer's eye throughout the work, however the method of consumption is up to the viewers discretion. For written works, there is much more structure, and expectation of reading from start to finish, but this method is not as strictly enforced by the medium, in the lack of time requirement and lack of automation of play.</p></div>
    <div className='paragraph'><p>Though these are significant advantages, confining a medium to a singular state also has major disadvantages. The most notable are the loss of change and loss of subtlety. The element of time adds a factor of change over time, which is an element of reality that every viewer is familiar with. Showing elements in motion in a stagnant medium provides its own difficulty, as any instance of motion in a comic is actually a stationary object with environmental implications of motion. An example of this is a stationary ball with “speed lines,” lines that give the impression of speed by tracing the path of a moving object. In this case, the ball is not actually moving, but the observed environment tells the viewer that it is. This compromise is not necessary in video, because any change in time can be directly shown, via change in time.</p></div>
    <div className='paragraph'><p>Similarly, elements of subtlety are lost between the forms; as what is considered subtlety is often minor details or minor changes over time. These subtleties can be minor in the sense of lacking size relative to the greater scene or lacking duration relative to the much longer duration of the scene, within which they are contained. Examples of these in live action film can be found in the work of character actors, such as Jake Gyllenhaal and Anthony Hopkins. Jake Gyllenhaal is extremely expressive in how he uses his eyes to match character emotion. In the 2013 film Prisoners, he twitches his eyes with an increased frequency as the movie progresses, mirroring his character’s increased urgency and heightened desire to solve the case. Anthony Hopkins, in a similarly subtle manner, specifically paces his words, and changing his expression as he moves through a sentence. This is done in order to tell story of the character’s internal shifts, and creates a deeper interaction with the scene. Details like these are impractical to replicate in a comic form. Catching every single eye movement is something that the mind is able to comprehend and understand in real time, but would require pages of images to properly replicate in a comic. Similarly, a sense of scene pacing in minor detail throughout a single sentence cannot be effectively replicated in the time devoid medium of comics.</p></div>
    <div className='paragraph'><p>Despite the significant discrepancies in the abilities of these two forms, the purposes of comics and videos are often the same. A video can aim to tell a narrative, such as Frankenstein, or deliver a political message, such as Citizenfour; while comics do the same in graphic novels and political cartoons. What is important about this comparison is how comics compensate for their disadvantages as a medium. Where comics lose subtlety and change, they often compensate with exaggeration. A previously mentioned example of exaggeration is the speed lines used to express movement by exaggerating its effects on the environment. Similarly, abstract shapes and details are often used to express physical meaning which would normally be conveyed by subtle details in traditional films. An example is the use of violent, jagged lines and popped veins to represent anger and the use of curling lines and question marks to represent confusions. Similar effects are achieved by coloring scenes, making certain pages of a comic seem more energetic or mellow depending on the desire of the creator. It is important to note that these compensations are stylistic, and not due to the specific ability of the medium. This same exaggeration can be seen in the use of special effects in live action video. The main importance of this exaggeration in comics is that it is used because of the limitations of the medium, when compared to a medium like live action video.</p></div>
    <hr></hr>
    <div className='paragraph'><p>The abilities and limitations of comics are what make them interesting as a medium. By taking the abstract elements of literary works and the interpretive elements of visual works, comics are able to convey a focused meaning in a consumable and accessible form. In melding these two elements together, comics can tie a viewer's interpretation and perspective to the message and meaning of the creator. By relying on exaggeration, comics are able to highlight the important information, bringing more depth in meaning and making the message more understandable and explicit in a visual form. All of these factors contribute to a comic’s ability as a narrative and political tool and to comic’s general intrigue as a form.</p></div>

    <hr></hr>
    <div className='title'>Links</div>
    <hr></hr>

    <div className='content_block'>
    <ul>
        <li><ALink href='http://scottmccloud.com/2-print/1-uc/'>Understanding Comics by Scott McCloud</ALink></li>
    </ul>
    </div>
  </Layout>
)

export default ComicsPage
