import React from 'react'

import Layout from '../../components/layout'
import ALink from '../../components/alink'

const WhatIsGamePage = () => (
  <Layout title='“What is a Game?”'>
    <div className='page_title'>“What is a Game?”</div>
    <div className='page_subtitle'>Multi-Level Understanding of Games as Media</div>

    <div className='note'><p>This paper was written as coursework for CMS.400, Media Systems and Texts.<br/>It's kinda bad.<br/>December 2016</p></div>

    <div className='paragraph'><p>When making a comparison, a common ground should be established in order for differences to be made known. In a similar way, for a piece of media to be analyzed and compared to previous works, a firm understanding of the media form should be established. With traditional media forms, the understanding of the form is generally clear. Traditional media forms have precedents and rules by which the form can be understood and defined. This does not hold true for games as a medium.</p></div>
    <div className='paragraph'><p>The variety and interactivity offered by games makes them interesting as a media form. Games are a new field in media studies, relative to the more traditional fields of oral tradition, literature, and film. In addition, games have an element of interactivity, giving them a large variety in form. For this reason, a singular, understandable model for games is less clear cut. The medium of games should be understood by a model that is both descriptive, defining a game, as well as a differentiative, classifying games for more productive comparison. This can be seen by analyzing the models of Jesper Juul and Keith Burgun.</p></div>
    <hr></hr>
    <div className='paragraph'><p>In the book Half-Real, Jesper Juul creates and explores a model used to describe games. His model outlines six features which are necessary for something to be considered a game. The features are as follows:</p></div>
    <div className=''><ol>
      <li>a rule-based formal system;</li>
      <li>with variable and quantifiable outcomes;</li>
      <li>where different outcomes are assigned different values;</li>
      <li>where the player exerts effort in order to influence the outcome;</li>
      <li>the player feels emotionally attached to the outcome;</li>
      <li>and the consequences of the activity are optional and negotiable.</li>
    </ol></div>
    <div className='paragraph_unindent'><p>These features work on three different levels: the level of the game itself, the level of the game’s relation to the player, and the level of the game’s relation to the rest of the world.</p></div>
    <div className='paragraph'><p>Juul’s model is interesting in how it separates games into levels. In doing so, it is able to encapsulate the multiple views of games as a medium. The first view addressed is the view of “Games as Rules.” This is the view that games are a set of rules with which the player interacts. These rules make-up the game’s system, through which the elements of emergence and progression are seen. Emergence is the game structure where relatively few rules yield a much larger variety in game structure. This element of games is part of what differentiates them from more traditional media forms. Emergence brings depth in understanding to games, making it important when differentiating between game forms. Progression is the game structure that determines the sequence of a game's rules or states. This element of games is present in most other media forms; however, progression in games often has a variety unique to interactive media. Where other media forms, such as films and literature, have a linear progression for consumption, game progression can show diversity based on player interaction. This can be seen in the multiple ending or outcomes of a variety of games. This view of games as unique is represented by the first level of the model, the level of the game itself. The existence of games as a system of rules is directly addressed by the first feature. The element of choice and variety are acknowledged by the second feature. The meaning of the choices, through disparity of outcomes, is recognized in the third feature. In these first three features, the model fully addresses the view of games as rules.</p></div>
    <div className='paragraph'><p>The second view addressed is the view of “Games as Fiction.” This is the view of games as stories or settings with which the player interacts for a desired result. This is the second level of the model, the game’s relation to the player. The fourth feature addresses interactivity, in the player interacting with the rules to affect the outcome. The fifth feature bring motivation for interactivity, the emotional attachment to the outcome. This is where the view of games as fiction is expressed. The fictional nature of games is what creates player motivation. In more complex, narrative focused games, the fictional elements are more explicit and the motivations are more traditionally fictionally. An example would be a game with the goal of slaying a monster to save the world. All elements involved in the setting are clearly fictional in a traditional sense; however they can still motivate a player to act. This element of motivation extends too much simpler games as well. An example would be a simple score counter with a recorded high score. The motivation is given by the score, and passing the benchmark; but the score itself is fictional, meaningless outside of the context of the game.</p></div>
    <div className='paragraph'><p>The third and final level of Juul’s model is the game’s relation to the world. This level addresses the view of games as “half-real,” and is defined by the sixth feature. This feature separates the consequences from the media. In this way, a piece of media considered a game will have a real set of rules and fiction; but these elements do not need to have consequences in reality. This is what allows a game to exist as an independent piece of media.</p></div>
    <div className='paragraph'><p>Juul’s model is a good baseline for describing a game. It incorporates many views of games, condensing them into relatively simple rules. Where this model is lacking is the ability to differentiate between forms of games. This can be seen in comparing the games four square, tic-tac-toe, OpenSorcery, and Dark Souls. While all four of these examples fit the criteria features of games; their rules and methods of interaction are so far removed from each other that comparison is less productive. The written word parallel would be comparing a novel to a haiku; as both are forms of written words that follow the same rules of grammar and literature. The comparison would be useful in understanding the differences in media forms, between the haiku form and novel form; but, when looking at the media itself, such a comparison is less productive. Thus, it is valuable to have a model differentiating games. The model should classifying them so that can be analyzed in the context of their more specific form, rather than the form of games as a whole. For this reason, Burgun’s model will be analyzed as well.</p></div>
    <hr></hr>
    <div className='paragraph'><p>In the article The Four Interactive Forms, Keith Burgun explains a model to describe games, based on a deconstructive approach of breaking games down to their simplest form. Burgun’s model has four levels, with each level producing a different value when interacted with by a player. The levels are as follows:</p></div>
    <div className=''><ol>
      <li>Toys: System<br/>Value: Mapping</li>
      <li>Puzzle: System+Solution<br/>Value: Solving</li>
      <li>Contest: System+Solution+Measurement<br/>Value: Evaluation</li>
      <li>Game: System+Solution+Measurement+Decisions<br/>Value: Understanding</li>
    </ol></div>
    <div className='paragraph_unindent'><p>The first thing to note about this model is that the fourth level, “game,” does not refer to games as a whole medium, but to a specific form that games can take. In the model, Burgun uses the term “Interactive System” as a substitute for the more general usage of the word game. For clarity and consistency, the term “complex game” will be used as the name of the fourth level for this analysis. The term “game” will continue to be in reference to the medium as a whole.</p></div>
    <div className='paragraph'><p>The first form is the toy, an interactive system with no set goal. The value of a toy is “mapping,” which is the discovery of results for given system inputs. In comparison to Juul’s model, this baseline definition of a game is barebones. It expresses brevity to the point of missing important elements in defining a games, the optional nature of consequence. Without this element of definition, any system that is intractable could be considered a game. From here, a toy is used as a basic form, with each additional level building on previous ones.</p></div>
    <div className='paragraph'><p>The second form is the puzzle, an interactive form with a set goal. The value of a puzzle is “solving,” or reaching the goal. With this definition, a traditional jigsaw puzzle can be considered a game of this form, allowing for easier comparison to other games of similar form. This is valuable because it gives a basis for comparison between games such as jigsaw puzzles, rubiks cubes, and Sudoku. All three of these examples can be assessed on their use of systems, use of their solutions, and in what ways the produce value in being solved. These metrics for comparison are not as easily understood using a purely definitive model, such as Juul’s.</p></div>
    <div className='paragraph'><p>The third form is the contest, an interactive system and goal that adds a session limitation. The value of a contest is “measurement,” which is the quantification of the solution or results. This session limitation can take many forms, though the most common are time limits and distances. Similar to the puzzle form, this additional element of measurement adds an additional metric for comparison.</p></div>
    <div className='paragraph'><p>The fourth and final form is the complex game, which takes a contest and obfuscates information. The value of this form is “understanding,” which is learning how the game works and applying this understanding to make better decisions. This definition of form makes implicit sense with many computer games, which can easily obfuscate large amounts game information. This seems less applicable to traditional complex games, such as Chess and Go. Despite the seeming lack of obfuscation, a game like Chess still falls into this category. With Chess, there are rules defining piece movement, a goal of eliminating the opponent, and a metric of measurement in both the scoring system and the final win or lose state. Obfuscation comes in not in obfuscation of the game state, but in obfuscation of the meaning of the game state. With complex games like Chess and Go, the game state is clearly visible to all participants, but the understanding of meaning varies between players. A new player might lose a piece or lose a part of the board and think that it a purely negative result; however, a more experienced player might use these losses as a price to ensure gain later in the match. This information is not explicitly states in the game state, but can be understood through experience and play. Complex games are where the element of emergence most makes itself known. Through simple rules, emergence creates a large amount of depth for a player to understand.</p></div>
    <div className='paragraph'><p>Burgun’s model is a good means of understanding and comparing games within themselves. The forms he outlines are valuable in their niche of being more specific than the general medium of games, but still less specific than the established game systems of genre. There are two important, additional benefits of using this model. The first is it allows for complex games to be understood as and compared to lower-level, simpler games. This classification allows for easier cross form comparison, by establishing from the start which elements of the game are directly comparable and which element are lacking between the forms. The second value is the ability for complex games to be understood on multiple levels. A more traditional example of multi-level analysis would be a sport, such as baseball. Understanding is an important element of the game, but the physical nature also gives it an aspect of measurement. This model allows for analysis in both contexts. As a more modern example, a sandbox game such as Minecraft, the game is a complex game, but the value aimed for might be that of a toy. In knowing this, the game can be analyzed in how effective it is in both forms. Similarly, a puzzle game, such as portal, might aim for a balance of both the understanding of a complex game and the solving of a puzzle. This model allows it to be designed with both contexts in mind.</p></div>
    <hr></hr>
    <div className='paragraph'><p>Burgun’s model is comprehensive in explaining the purposes and values of specific interactive forms. Where this model lacks is definition. As stated with the first form, there isn’t a good baseline definition of what qualifies as a game. The condition given, having rules and outcomes, is too broad a definition to only include games. As can be seen from the analysis, though these models lack independently, using both provides the most range of effective analysis. As a result, a model for understanding games should have both a strong descriptive component and a differentiative model for classification.</p></div>

    <hr></hr>
    <div className='title'>Links</div>
    <hr></hr>

    <div className='content_block'>
    <ul>
        <li><ALink href='https://mitpress.mit.edu/books/half-real'>Half-Real by Jesper Juul</ALink></li>
        <li><ALink href='http://keithburgun.net/interactive-forms/'>The Four Interactive Forms by Keith Burgun</ALink></li>
    </ul>
    </div>
  </Layout>
)

export default WhatIsGamePage
